name: ir1
channels:
  - defaults
  - conda-forge
dependencies:
  - gensim==3.8.3
  - ipywidgets==7.5.1
  - matplotlib==3.1.2
  - nltk==3.4.5
  - numpy==1.18.1
  - requests==2.22.0
  - tqdm==4.42.0
  - python==3.6.5
